#include the tokyo-night config
include ./tokyo-night.conf

#hide_window_decorations yes
map f11 toggle_fullscreen

#nerd font so it works in neovim
font_family      0xProto Nerd Font Mono
font_size        12.0

#define initial window size
remember_window_size no
initial_window_width  80c
initial_window_height 24c

#heigh 
adjust_line_height  0
adjust_column_width 0

#matches screen refresh rate
sync_to_monitor yes

#color
term xterm-kitty

scrollback_lines 10000

allow_remote_control yes

shell_integration enabled
window_padding_width 4
copy_on_select yes

enable_audio_bell no

#some keys for tabs
map ctrl+shift+l next_tab
map ctrl+shift+h previous_tab

# better tabs
tab_bar_style powerline
tab_powerline_style slanted
