#include the tokyo-night config
include ./tokyo-night.conf

#nerd font so it works in neovim
font_family      0xProto Nerd Font Mono
font_size        12.0

#define initial window size
initial_window_width  80c
initial_window_height 24c

#heigh 
adjust_line_height  0
adjust_column_width 0

#matches screen refresh rate
sync_to_monitor yes

#color
term xterm-256color

scrollback_lines 10000

shell_integration enabled
window_padding_width 4
copy_on_select yes

enable_audio_bell yes
